# Generated by Django 3.2.18 on 2023-06-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addrres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('town', models.CharField(max_length=30)),
                ('street', models.CharField(max_length=30)),
                ('number', models.DateField()),
            ],
        ),
    ]
