# Generated by Django 3.2.18 on 2023-06-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0002_addrres'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addrres',
            new_name='Address',
        ),
    ]
