# Generated by Django 3.2.18 on 2023-06-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0003_rename_addrres_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
