# Generated by Django 3.2.18 on 2023-11-26 09:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0010_auto_20230910_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puple',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.person'),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('puple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.puple')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myschool.teacher')),
            ],
        ),
    ]
