# Generated by Django 3.2.18 on 2023-11-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0011_myschool'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myschool',
        ),
    ]
