# Generated by Django 3.2.18 on 2023-12-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myschool', '0011_auto_20231126_0916'),
        ('myschool', '0012_delete_myschool'),
    ]

    operations = [
    ]
